### ISSUE TITLE
Getting list of All Offers (not only the published ones)

### ISSUE THREAD

**Issue by kafeinet** [Cdiscount/API-MarketPlace-SDK-PHP#12]
Hi,

Working from your sample /Offer/GetOfferList.php, I'm unable to see the list of ALL our offers, it only shows the published ones.

Is there a filter or something I can use to show all the offers ?

Thx,

**Comment by gregz1** [comment]
hello, 

I confirm this method only returns published offers
You can get all offers with the paginated method : GetOfferListPaginated.
This method also returns additional information like information on the "best offer" on your products

rgrds
