### ISSUE TITLE
install sdk in symfony3  project

### ISSUE THREAD

**Issue by BT2016-DRUPAL** [Cdiscount/API-MarketPlace-SDK-PHP#15]
I can't use the lib when i call  `new \Sdk\ApiClient\CDSApiClient();`  i have the error CDSApiClient can't be found in namespace  Sdk\ApiClient.

I'm using symfony3  version 3.1
the sdk is installed via composer `composer require cdiscount/sdkphpapi dev-master` 
anf of course i've made a `composer dump-autoload` after the install

Can you please help me solve this issue ?
Or
Is there a bundle version version of the sdk compatible with symfony ?

**Comment by gregz1** [comment]
This issue was moved to gregz1/MyRepo#1

**Comment by gregz1** [comment]
This issue was moved to gregz1/MyRepo#2

**Comment by gregz1** [comment]
This issue was moved to gregz1/MyRepo#3
