### ISSUE TITLE
Error : Not enough quota available (1 requested and 0 available)

### ISSUE THREAD

**Issue by hzhihu** [Cdiscount/API-MarketPlace-SDK-PHP#22]
Error : Not enough quota available (1 requested and 0 available)
Why??
Cdiscount support can help me.

Thanks

**Comment by gregz1** [comment]
This error means you have reach the number of call allowed for this method for the current hour.
If you have this error message you only have to wait for an hour.

regards

**Comment by ltlwill** [comment]
laji

**Comment by ltlwill** [comment]
laji cd

**Comment by ltlwill** [comment]
la ji  cd
