### ISSUE TITLE
Script error in GetSellerIndicatorsResponse.php

### ISSUE THREAD

**Issue by 20100uno** [Cdiscount/API-MarketPlace-SDK-PHP#3]
An issue on line 112 in file \src\core\Soap\Seller\Response\GetSellerIndicatorsResponse.php

Replace:
 $sellerIndicator->setValueD30(floatval(['ValueD30']));
By:
 $sellerIndicator->setValueD30(floatval($sellerIndicatorXML['ValueD30']));

Vincent

**Comment by guillaumecochard** [comment]
Hi, thanks for reporting the issue.
It has been fixed in 1.0.6
