### ISSUE TITLE
Shipping code

### ISSUE THREAD

**Issue by josamho** [Cdiscount/API-MarketPlace-SDK-PHP#31]
Hello !

I'm trying to get the ShippingCode of my order to know the "delivery method".
I already asked the CDISCOUNT support and they say to explain my problem here.

In the xml i get the shipping code, but when with the code i get a object without the Shipping code (return 'NULL')
I attach the xml and the object !

[object order.txt](https://github.com/Cdiscount/API-MarketPlace-SDK-PHP/files/1401068/object.order.txt)
[xml request.txt](https://github.com/Cdiscount/API-MarketPlace-SDK-PHP/files/1401069/xml.request.txt)

**Comment by gregz1** [comment]
hello 
it should have been solved by the Commit of 19th of  Dec

regards
