### ISSUE TITLE
SubmitOfferPackage: throttling limit for offer integration

### ISSUE THREAD

**Issue by tazplan** [Cdiscount/API-MarketPlace-SDK-PHP#38]
Hello,
Few questions about the SubmitOfferPackage:
- how many zip package can I submit on daily or hourly? any limit? if yes, what is the recovery time if the limit is exceeded?
- how many offer per xml file can I include?

**Comment by gregz1** [comment]
Hello,

The API quota are applied on the number of call to the methods by hour.
The counter of call is reinitialized every hour.

If you include more than 300 000 offers in your package you are not sure that your package will be integrated.
Our advise is to stay below 200 000 offers in your package.

regards

**Comment by lexo13** [comment]
Have you an XML example zip package please because i've always errors

`KO 2123 Specified part does not exist in the package. `

**Comment by gregz1** [comment]
it seems you already find it but if somebody else is looking for the information ^^ : 
https://dev.cdiscount.com/marketplace/?page_id=1198

regards
