### ISSUE TITLE
Fatal error class Zend\Validator\NotEmpty' not found

### ISSUE THREAD

**Issue by 20100uno** [Cdiscount/API-MarketPlace-SDK-PHP#4]
Could you please verify if it is working on your side ?
Fatal error: Class 'Zend\Validator\NotEmpty' not found 
in /sdk/src/core/ConfigTools/ConfigFileLoader.php on line 45

**Comment by guillaumecochard** [comment]
Hi, do you still have the issue ?
I think it's juste because you have to run a composer update in the root path of the SDK to download the zend framework r

**Comment by 20100uno** [comment]
Hi

Thanks a lot for your answer.

I've to try in 1 week only (no computer available) !

See you


Vincent HUNAULT
PAVILOU WEB SASU
06 87 25 25 70
11 rue Henri Pourrat
63430 Les Martres d'Artière

2017-02-22 9:41 GMT+01:00 Guillaume COCHARD <notifications@github.com>:

**Comment by 20100uno** [comment]
Unfortunately my php version is 5.3 (5.5 required)...

**Comment by guillaumecochard** [comment]
Yes sorry, 5.3 is no longer supported.
Can you upgrade your PHP version ?

**Comment by stephaneconnect** [comment]
Hello, I just installed WAMP with PHP Version 5.6.25 but i have the same message 'Zend\Validator\NotEmpty' not found in \sdk\src\core\ConfigTools\ConfigFileLoader.php on line 45.  Have you got an idea ? Thanks

**Comment by 20100uno** [comment]
Hello,
With PHP Version 5.6, I've got an error 500 on all pages, any idea ?

**Comment by oliverstoned** [comment]
Hello,

Have you install with composer the Zend Framework dependencies.
I had the same error and i have install this dependencies and i call to auload.php in vendor

**Comment by 20100uno** [comment]
It works now, thanks!
