### ISSUE TITLE
Can"t update offers

### ISSUE THREAD

**Issue by Petoches** [Cdiscount/API-MarketPlace-SDK-PHP#66]
Hello,

Can't find a way to update my offers. Used the sample by cdiscount only editing the offer.xml
always getting as a result : `<ErrorMessage xmlns="http://schemas.datacontract.org/2004/07/Cdiscount.Framework.Core.Communication.Messages">Impossible de lire les rapports du package demandé</ErrorMessage>`

Thanks.

**Comment by lulumahot** [comment]
Hello @Petoches, I'm facing the same issue. Did you manage to solve it ?

**Comment by Petoches** [comment]
Hello @lulumahot yep , sadly i won't be a great help, the problem was resolved by itself. The next day with the same package everything worked fine ... Maybe a problem on some process ( i was using the sandbox at the time ).
