### ISSUE TITLE
URGENT: Amount cent values are cut off

### ISSUE THREAD

**Issue by M-Mommsen** [Cdiscount/API-MarketPlace-SDK-PHP#8]
for example in :
API-MarketPlace-SDK-PHP/sdk/src/core/Soap/Order/GetOrderListResponse.php
Lines 169,170 and more use intval() on a currency value - so all values are without cents - which makes them useless and wrong!

$orderObj->setSiteCommissionPromisedAmount(**intval**($order['SiteCommissionPromisedAmount']));

I suggest using floatval() instead and to change the documentation accordingly!

**Comment by guillaumecochard** [comment]
Hi, thanks for reporting the issue. It has been fixed on master

**Comment by R-Wirtz** [comment]
Hi,
In file "API-MarketPlace-SDK-PHP/sdk/src/core/Soap/Order/GetOrderListResponse.php" the lines 217 and 318 are still intval. I suggest to change them to floatval too.

Thanks,
Robert

**Comment by guillaumecochard** [comment]
Hi @R-Wirtz, thanks, just fixed now on master
