### ISSUE TITLE
Get ORder List

### ISSUE THREAD

**Issue by udhayavanan** [Cdiscount/API-MarketPlace-SDK-PHP#9]
Hi, in Get order list, Orders Retrieved but in response i cannot get token id and orderline list. 
im getting following error repeatedly
'Vous ne pouvez obtenir les alias de clients dont la commande est expédiée depuis plus de 4 semaines' means '
You can not get aliases from customers whose order has been shipped for more than 4 weeks'
Regarding this issue mailed cdiscount development team too. help me to fix if mistake in code development.

**Comment by guillaumecochard** [comment]
Hi, can you send me the Soap enveloppe generated (removing your token).
Thanks

**Comment by udhayavanan** [comment]
There are two envelopes. kind of header element and orders element which one needed?

**Comment by guillaumecochard** [comment]
Can you send me both ?
Don't forget to remove your token from the enveloppe. Thanks

**Comment by udhayavanan** [comment]
I attached two txt files. pls change txt to xml to check in browser. thank you.

[Header_Section.txt](https://github.com/Cdiscount/API-MarketPlace-SDK-PHP/files/827217/Header_Section.txt)
[Order_Details..txt](https://github.com/Cdiscount/API-MarketPlace-SDK-PHP/files/827216/Order_Details.txt)

**Comment by guillaumecochard** [comment]
Thanks, I update your message to remove the attached files.
We will give you feedback of the fix

**Comment by guillaumecochard** [comment]
It's seems that you don't have the last version.
Can you please give me your sdk/version.txt number ?
Thanks

**Comment by udhayavanan** [comment]
Following version i used. 
Version number : 0.0.1
Version date   : 14112016

**Comment by guillaumecochard** [comment]
Okay, we are now in 1.0.8.
That's probably why you have the issue.
Please upgrade to 1.0.8

**Comment by udhayavanan** [comment]
ok let me try. and update soon thank you very much

**Comment by udhayavanan** [comment]
when i tried with new version (note that vendor directory is not exist in updated version). it throws some error. but i copied old version's vendor folder also tried with new version. it runs but token id is invalid. is it there api credentials authenticated based ip alone or from which base url it requestss also.

**Comment by udhayavanan** [comment]
above issue has occured in 1.0.7 version itself

**Comment by udhayavanan** [comment]
this issue not occurred in 1.0.5 version. token generated succssfully. will update status soon.

**Comment by udhayavanan** [comment]
I used 1.0.8 version and used store credentials instead of api credentials. it worked.
